name: Test Action

on:
  push:
    tags:
      - 'test-action-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Action
        id: test
        uses: ./ # Uses an action in the root directory
        with:
        #   upyun_token: "test-token"
        # 在 Settings->Secrets 配置 UPYUN_TOKEN
          upyun_token: ${{ secrets.UPYUN_TOKEN }}
          # 要刷新的url, 支持匹配符 *, 多个url中间用 \n 隔开
          refresh_cache_urls: "https://moeci.com/*"


      # Use the output from the `test` step
      - name: Get the output upyun_response
        run: echo "The output was ${{ steps.test.outputs.upyun_response }}"

